[2024-03-10T13:16:12.492+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:16:09.628401+00:00 [queued]>
[2024-03-10T13:16:12.509+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:16:09.628401+00:00 [queued]>
[2024-03-10T13:16:12.510+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-10T13:16:12.535+0000] {taskinstance.py:2214} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-03-10 13:16:09.628401+00:00
[2024-03-10T13:16:12.542+0000] {standard_task_runner.py:60} INFO - Started process 593 to run task
[2024-03-10T13:16:12.547+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'netflix_etl_dag', 'is_api_available', 'manual__2024-03-10T13:16:09.628401+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/netflix_dag.py', '--cfg-path', '/tmp/tmps4oc1ssj']
[2024-03-10T13:16:12.549+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask is_api_available
[2024-03-10T13:16:12.611+0000] {task_command.py:423} INFO - Running <TaskInstance: netflix_etl_dag.is_api_available manual__2024-03-10T13:16:09.628401+00:00 [running]> on host aaa4b1109113
[2024-03-10T13:16:12.703+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='anamsken60@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='netflix_etl_dag' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T13:16:09.628401+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-10T13:16:09.628401+00:00'
[2024-03-10T13:16:12.705+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:16:12.717+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:16:13.982+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:16:13.983+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:17:14.000+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:17:14.021+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:17:14.737+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:17:14.771+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:18:14.834+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:18:14.846+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:18:38.651+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:18:38.653+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:19:38.672+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:19:38.809+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:19:39.274+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:19:39.275+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:20:39.280+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:20:39.293+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:20:52.286+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:20:52.287+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:21:52.334+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:21:52.345+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:21:53.352+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:21:53.354+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:22:53.378+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:22:53.392+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:22:54.553+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:22:54.554+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:23:54.615+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:23:54.677+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:23:55.269+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:23:55.270+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:24:55.321+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:24:55.347+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:24:55.887+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:24:55.889+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:25:55.922+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:25:55.931+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:25:56.621+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:25:56.624+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:26:56.682+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:26:56.704+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:26:57.219+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:26:57.219+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:27:57.164+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:27:57.231+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:27:57.797+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:27:57.798+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:28:57.849+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:28:57.863+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:28:58.340+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:28:58.342+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
[2024-03-10T13:29:58.407+0000] {http.py:137} INFO - Poking: unogs/
[2024-03-10T13:29:58.452+0000] {base.py:83} INFO - Using connection ID 'netflix_api' for task execution.
[2024-03-10T13:29:59.371+0000] {http.py:192} ERROR - HTTP error: Not Found
[2024-03-10T13:29:59.373+0000] {http.py:193} ERROR - {"message":"no Route matched with those values"}
